mexc:
  api_key: "mx0vglNnaHmyUVp3JG"
  secret_key: "your_secret_key_here"
  base_urls:
    spot: "https://api.mexc.com"
    contract: "https://contract.mexc.com"
  timeout: 10

logging:
  log_dir: "logs"
  log_level: "DEBUG"
  console_log_level: "DEBUG"
  file_log_level: "INFO"
  log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  max_log_files: 100

funding:
  top_n_symbols: 5
  time_windows:
    daily_days_back: 3
    hourly_hours_back: 8
    five_min_hours_before: 4
    one_min_minutes_before: 30
    one_min_minutes_after: 15